# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7dd0a84c3f63e213f40fd8572ad1a2283a297366d300131b36337c91119cd33ac28296c1a74329daa16780166c27d139ea2eba4901caaa3bf7210cc8ef7d3a9a

test:
  secret_key_base: 7713cc703a81790a7d727162d25a60be161f92962ac9ff16b9e545194ce8313cafcd9f0dbb6bb331e9a04eab887e5f4e3413281a9219818a94d428cca49a0e3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
